@extends('layouts.app')

@section('title', $report->title)

@section('content')
<a href="{{ route('admin.ai-reports.index') }}" class="text-sm text-violet-700 hover:underline">← AI reports</a>

<div class="mt-4 flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
    <div>
        <p class="text-2xl">{{ $report->type->icon() }}</p>
        <h1 class="text-2xl font-bold">{{ $report->title }}</h1>
        <p class="text-sm text-slate-500">
            {{ $report->report_date->format('l, d M Y') }}
            @if ($report->user) · MR: {{ $report->user->name }} @endif
            · Generated by {{ $report->generator->name }}
        </p>
    </div>
    @if ($aiAvailable)
        <form method="POST" action="{{ route('admin.ai-reports.generate') }}">
            @csrf
            <input type="hidden" name="type" value="{{ $report->type->value }}">
            <input type="hidden" name="user_id" value="{{ $report->user_id }}">
            <input type="hidden" name="force" value="1">
            <button type="submit" class="rounded-lg border border-violet-300 px-4 py-2 text-sm text-violet-700 hover:bg-violet-50">Regenerate</button>
        </form>
    @endif
</div>

<div class="mt-8 rounded-2xl border bg-white p-6 shadow-sm">
    @include('partials.ai-report-content', ['report' => $report])
</div>
@endsection
